// flow-typed signature: 65e09a462d23dee69755e10dc072529c
// flow-typed version: <<STUB>>/iconv-lite_v^0.4.23/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'iconv-lite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'iconv-lite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'iconv-lite/encodings/dbcs-codec' {
  declare module.exports: any;
}

declare module 'iconv-lite/encodings/dbcs-data' {
  declare module.exports: any;
}

declare module 'iconv-lite/encodings/index' {
  declare module.exports: any;
}

declare module 'iconv-lite/encodings/internal' {
  declare module.exports: any;
}

declare module 'iconv-lite/encodings/sbcs-codec' {
  declare module.exports: any;
}

declare module 'iconv-lite/encodings/sbcs-data-generated' {
  declare module.exports: any;
}

declare module 'iconv-lite/encodings/sbcs-data' {
  declare module.exports: any;
}

declare module 'iconv-lite/encodings/utf16' {
  declare module.exports: any;
}

declare module 'iconv-lite/encodings/utf7' {
  declare module.exports: any;
}

declare module 'iconv-lite/lib/bom-handling' {
  declare module.exports: any;
}

declare module 'iconv-lite/lib/extend-node' {
  declare module.exports: any;
}

declare module 'iconv-lite/lib/index' {
  declare module.exports: any;
}

declare module 'iconv-lite/lib/streams' {
  declare module.exports: any;
}

// Filename aliases
declare module 'iconv-lite/encodings/dbcs-codec.js' {
  declare module.exports: $Exports<'iconv-lite/encodings/dbcs-codec'>;
}
declare module 'iconv-lite/encodings/dbcs-data.js' {
  declare module.exports: $Exports<'iconv-lite/encodings/dbcs-data'>;
}
declare module 'iconv-lite/encodings/index.js' {
  declare module.exports: $Exports<'iconv-lite/encodings/index'>;
}
declare module 'iconv-lite/encodings/internal.js' {
  declare module.exports: $Exports<'iconv-lite/encodings/internal'>;
}
declare module 'iconv-lite/encodings/sbcs-codec.js' {
  declare module.exports: $Exports<'iconv-lite/encodings/sbcs-codec'>;
}
declare module 'iconv-lite/encodings/sbcs-data-generated.js' {
  declare module.exports: $Exports<'iconv-lite/encodings/sbcs-data-generated'>;
}
declare module 'iconv-lite/encodings/sbcs-data.js' {
  declare module.exports: $Exports<'iconv-lite/encodings/sbcs-data'>;
}
declare module 'iconv-lite/encodings/utf16.js' {
  declare module.exports: $Exports<'iconv-lite/encodings/utf16'>;
}
declare module 'iconv-lite/encodings/utf7.js' {
  declare module.exports: $Exports<'iconv-lite/encodings/utf7'>;
}
declare module 'iconv-lite/lib/bom-handling.js' {
  declare module.exports: $Exports<'iconv-lite/lib/bom-handling'>;
}
declare module 'iconv-lite/lib/extend-node.js' {
  declare module.exports: $Exports<'iconv-lite/lib/extend-node'>;
}
declare module 'iconv-lite/lib/index.js' {
  declare module.exports: $Exports<'iconv-lite/lib/index'>;
}
declare module 'iconv-lite/lib/streams.js' {
  declare module.exports: $Exports<'iconv-lite/lib/streams'>;
}
